package com.vyttah.goaml.service.report.pdf;

import com.vyttah.goaml.domain.generated.Report;
import com.vyttah.goaml.engine.marshal.ReportMarshaller;
import com.vyttah.goaml.model.dto.report.DpmsrReportPayload;
import com.vyttah.goaml.repository.tenant.TenantRepository;
import com.vyttah.goaml.service.report.ReportDetail;
import com.vyttah.goaml.service.report.ReportExceptions;
import com.vyttah.goaml.service.report.ReportPreview;
import com.vyttah.goaml.service.report.ReportService;
import org.springframework.stereotype.Service;

import java.nio.charset.StandardCharsets;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.Optional;
import java.util.UUID;

/**
 * Orchestrates DPMSR report PDF generation for the REST layer: assembles the letterhead
 * {@link ReportHeaderContext} from the tenant + acting user, turns the stored/previewed goAML XML into the
 * typed {@link Report} tree, and hands both to {@link DpmsrPdfReportService}. Two entry points mirror the two
 * surfaces — a filed report (by id, from its persisted XML) and a pre-submit preview (from the posted
 * payload, nothing persisted).
 */
@Service
public class ReportPdfService {

    private static final DateTimeFormatter STAMP =
            DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm", Locale.ENGLISH);

    private final ReportService reportService;
    private final ReportMarshaller marshaller;
    private final TenantRepository tenantRepository;
    private final DpmsrPdfReportService pdf;

    public ReportPdfService(ReportService reportService, ReportMarshaller marshaller,
                            TenantRepository tenantRepository, DpmsrPdfReportService pdf) {
        this.reportService = reportService;
        this.marshaller = marshaller;
        this.tenantRepository = tenantRepository;
        this.pdf = pdf;
    }

    /** A generated PDF plus the download filename to stamp on the response. */
    public record PdfDocument(String filename, byte[] bytes) {}

    /** The filed report's PDF, rendered from its persisted goAML XML (VALID or INVALID). */
    public PdfDocument filed(UUID reportId, UUID tenantId, String userLabel) {
        com.vyttah.goaml.model.entity.report.Report entity = reportService.get(reportId);
        String xml = entity.getReportXml();
        if (xml == null || xml.isBlank()) {
            throw new ReportExceptions.ReportNotFoundException("Report has no generated XML: " + reportId);
        }
        ReportDetail detail = reportService.detail(reportId);
        Report typed = marshaller.unmarshal(xml.getBytes(StandardCharsets.UTF_8));
        TenantInfo tenant = tenantInfo(tenantId);
        ReportHeaderContext ctx = context(tenant, entity.getRentityId(), userLabel);
        byte[] bytes = pdf.render(typed, ctx, entity.getStatus(), tenant.jurisdiction(),
                detail.clientMetadata(), detail.validationMessages());
        return new PdfDocument("DPMSR_" + sanitize(entity.getEntityReference()) + ".pdf", bytes);
    }

    /** The pre-submit preview PDF of the exact payload the cockpit is about to file — nothing persisted. */
    public PdfDocument preview(DpmsrReportPayload payload, UUID tenantId, String userLabel) {
        ReportPreview pv = reportService.previewXml(payload, tenantId);
        Report typed = marshaller.unmarshal(pv.xml().getBytes(StandardCharsets.UTF_8));
        TenantInfo tenant = tenantInfo(tenantId);
        ReportHeaderContext ctx = context(tenant, typed.getRentityId(), userLabel);
        byte[] bytes = pdf.render(typed, ctx, pv.status() + " (preview — not yet filed)", tenant.jurisdiction(),
                payload.clientMetadata(), pv.messages());
        return new PdfDocument("DPMSR_" + sanitize(payload.entityReference()) + "_preview.pdf", bytes);
    }

    private ReportHeaderContext context(TenantInfo tenant, Integer rentityId, String userLabel) {
        String generatedBy = "Generated by " + (userLabel == null || userLabel.isBlank() ? "goAML" : userLabel);
        return new ReportHeaderContext(tenant.name(), rentityId, tenant.jurisdiction(),
                generatedBy, OffsetDateTime.now().format(STAMP));
    }

    private TenantInfo tenantInfo(UUID tenantId) {
        Optional<com.vyttah.goaml.model.entity.tenant.Tenant> t =
                tenantId == null ? Optional.empty() : tenantRepository.findById(tenantId);
        return new TenantInfo(
                t.map(com.vyttah.goaml.model.entity.tenant.Tenant::getName).orElse(null),
                t.map(com.vyttah.goaml.model.entity.tenant.Tenant::getJurisdictionCode).orElse("ae"));
    }

    private record TenantInfo(String name, String jurisdiction) {}

    private static String sanitize(String s) {
        if (s == null || s.isBlank()) {
            return "report";
        }
        return s.trim().replaceAll("[^\\w.\\-]+", "_").replaceAll("^_+|_+$", "");
    }
}
