package com.vyttah.goaml.model.dto.report;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.json.JsonMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.vyttah.goaml.domain.generated.Report;
import com.vyttah.goaml.domain.jackson.GeneratedEnumJacksonModule;
import com.vyttah.goaml.engine.build.ActivityReportBuilder;
import com.vyttah.goaml.engine.build.DpmsrReportBuilder;
import com.vyttah.goaml.engine.build.DpmsrReportInput;
import com.vyttah.goaml.engine.marshal.ReportMarshaller;
import com.vyttah.goaml.engine.validation.ValidationResult;
import com.vyttah.goaml.engine.validation.XsdSchemaValidator;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * XML-fidelity proof for the HYBRID cockpit flow: the fixture is the byte-exact wire shape the AML
 * cockpit's Create Transaction page now POSTs to {@code POST /api/v1/reports} (generated by the actual
 * frontend assembly code — assembleReport.ts + dpmsrPayload.ts — from a form mirroring a real accepted
 * portal filing, values anonymized). It must bind onto {@link DpmsrReportPayload}, build, and marshal
 * into XML that carries the same structure as the real production DPMSR downloaded from the FIU portal:
 * {@code entity_my_client} (with incorporation_legal_form / business / 1-char tax_reg_number-as-PEP),
 * a related-person UBO, a header {@code location}, and the full goods block (disposed_value, size,
 * registration_number, comments) — and it must pass the authoritative 5.0.2 XSD gate.
 */
class HybridCockpitWireFidelityTest {

    private final ReportMarshaller marshaller = new ReportMarshaller();
    private final XsdSchemaValidator xsd = new XsdSchemaValidator();

    // mirrors Spring Boot's auto-configured ObjectMapper: JavaTime + ISO dates + our generated-enum module
    private final JsonMapper mapper = JsonMapper.builder()
            .addModule(new JavaTimeModule())
            .addModule(new GeneratedEnumJacksonModule())
            .serializationInclusion(JsonInclude.Include.NON_NULL)
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
            .build();

    @Test
    void hybridCockpitPayloadBuildsPortalShapedXmlAndPassesTheXsdGate() throws IOException {
        DpmsrReportPayload payload = mapper.readValue(
                readResource("samples/hybrid-cockpit-wire-payload.json"), DpmsrReportPayload.class);

        DpmsrReportInput input = payload.toInput(21340);
        Report built = new DpmsrReportBuilder(new ActivityReportBuilder(), null, null, null).build(input);
        String xml = new String(marshaller.marshal(built), StandardCharsets.UTF_8);

        // The structure of the real accepted filing, element for element.
        assertThat(xml)
                // header: server-injected constants + the cockpit header fields
                .contains("<rentity_id>21340</rentity_id>")
                .contains("<submission_code>E</submission_code>")
                .contains("<report_code>DPMSR</report_code>")
                .contains("<entity_reference>PUR/SAMPLE/0001</entity_reference>")
                .contains("<currency_code_local>AED</currency_code_local>")
                // Location of Incident (header t_address)
                .contains("<location>")
                .contains("<address>Sample Gemplex 30-01-0001 Plot No: SAMPLE-PH2 Dubai</address>")
                .contains("<state>Dubai</state>")
                // the subject files as entity_my_client (the portal party type), NOT the lenient t_entity
                .contains("<entity_my_client>")
                .doesNotContain("<entity>")
                // portal field mappings: Business Activity -> incorporation_legal_form, Licensing
                // Authority -> business, PEP (Y/N) -> the 1-char tax_reg_number
                .contains("<incorporation_legal_form>WJDPS</incorporation_legal_form>")
                .contains("<business>Sample Licensing Authority</business>")
                .contains("<tax_reg_number>N</tax_reg_number>")
                .contains("<incorporation_state>Peru</incorporation_state>")
                .contains("<incorporation_country_code>PE</incorporation_country_code>")
                // the UBO rides as a related person with role + share percentage
                .contains("<related_persons>")
                .contains("<entity_related_person>")
                .contains("<role>UBO</role>")
                .contains("<share_percentage>100</share_percentage>")
                .contains("<last_name>UBOLAST</last_name>")
                // party narrative
                .contains("<reason>Sale of Gold Dore Bar</reason>")
                .contains("Payment is done to the SAMPLE ADMINISTRADORA S.A.C. account")
                // goods: the full portal set incl. Invoice Amount -> disposed_value
                .contains("<item_type>GOLD</item_type>")
                .contains("<estimated_value>882728.67</estimated_value>")
                .contains("<disposed_value>882728.67</disposed_value>")
                .contains("<currency_code>USD</currency_code>")
                .contains("<size>6021</size>")
                .contains("<size_uom>Grams</size_uom>")
                .contains("<registration_number>PUR/SAMPLE/0001</registration_number>")
                .contains("<comments>International Wire Transfer of USD 882728.67 payment done against the purchase of 6021.52 grams of gold dore bar</comments>")
                .contains("<status_code>PRCHS</status_code>")
                // indicator
                .contains("<indicator>DPMSJ</indicator>");

        // and the whole document passes the authoritative goAML 5.0.2 schema
        ValidationResult result = xsd.validate(xml.getBytes(StandardCharsets.UTF_8));
        assertThat(result.isValid())
                .as("hybrid cockpit XML must be XSD-valid; findings: %s", result)
                .isTrue();
    }

    @Test
    void naturalSubjectFilesAsPersonMyClientAndPassesTheXsdGate() throws IOException {
        // The natural-subject wire shape the cockpit emits when the my_client-required set is complete
        // (myClientGaps() == [] gates this client-side: names, birthdate, id, nationality, residence,
        // phone, a full identification document and the PEP flag).
        String json = """
                {
                  "entityReference": "TXN-SAMPLE-2",
                  "submissionDate": "2026-07-15T00:00:00Z",
                  "indicators": ["DPMSI"],
                  "parties": [{
                    "reason": "Buyer of gold bars",
                    "personMyClient": {
                      "gender": "F",
                      "firstName": "Lena",
                      "lastName": "Souza",
                      "birthdate": "1990-05-04T00:00:00Z",
                      "nationality1": "BR",
                      "residence": "AE",
                      "idNumber": "784199012345678",
                      "taxRegNumber": "N",
                      "phones": {"phone": [{"tphContactType": "BU", "tphCommunicationType": "L",
                        "tphCountryPrefix": "971", "tphNumber": "501234567"}]},
                      "identification": [{"type": "EID", "number": "784199012345678",
                        "issueDate": "2020-01-01T00:00:00Z", "expiryDate": "2030-01-01T00:00:00Z",
                        "issueCountry": "AE"}]
                    }
                  }],
                  "goods": [{"itemType": "GOLD", "statusCode": "SOLD", "estimatedValue": 60000,
                    "currencyCode": "AED", "description": "Gold bars"}]
                }
                """;
        DpmsrReportPayload payload = mapper.readValue(json, DpmsrReportPayload.class);
        Report built = new DpmsrReportBuilder(new ActivityReportBuilder(), null, null, null)
                .build(payload.toInput(21340));
        byte[] xml = marshaller.marshal(built);
        String s = new String(xml, StandardCharsets.UTF_8);

        assertThat(s)
                .contains("<person_my_client>")
                .doesNotContain("<person>")
                .contains("<gender>F</gender>")
                .contains("<tax_reg_number>N</tax_reg_number>")
                .contains("<identification>");

        ValidationResult result = xsd.validate(xml);
        assertThat(result.isValid())
                .as("person_my_client XML must be XSD-valid; findings: %s", result)
                .isTrue();
    }

    private static byte[] readResource(String path) throws IOException {
        try (InputStream in = Thread.currentThread().getContextClassLoader().getResourceAsStream(path)) {
            assertThat(in).as("test resource %s present on classpath", path).isNotNull();
            return in.readAllBytes();
        }
    }
}
