package com.vyttah.goaml.service.report.pdf;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.json.JsonMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.vyttah.goaml.domain.generated.Report;
import com.vyttah.goaml.domain.jackson.GeneratedEnumJacksonModule;
import com.vyttah.goaml.engine.build.ActivityReportBuilder;
import com.vyttah.goaml.engine.build.DpmsrReportBuilder;
import com.vyttah.goaml.engine.lookup.LookupService;
import com.vyttah.goaml.engine.marshal.ReportMarshaller;
import com.vyttah.goaml.model.dto.report.DpmsrReportPayload;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The DPMSR report PDF renders from a real (hybrid-cockpit) payload without error, produces a well-formed,
 * non-trivial PDF, and is driven by the same typed {@link Report} the engine files. We build the report from
 * the shared fidelity fixture, marshal→unmarshal to get the typed tree exactly as the PDF endpoint does, and
 * render. Also writes the PDF to {@code build/} for eyeball review. Pure — no Spring, no Docker.
 */
class DpmsrPdfReportServiceTest {

    private final JsonMapper mapper = JsonMapper.builder()
            .addModule(new JavaTimeModule())
            .addModule(new GeneratedEnumJacksonModule())
            .serializationInclusion(JsonInclude.Include.NON_NULL)
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
            .build();
    private final ReportMarshaller marshaller = new ReportMarshaller();
    private final DpmsrPdfReportService service = new DpmsrPdfReportService(new LookupService());

    @Test
    void rendersAWellFormedNonTrivialPdfFromTheHybridPayload() throws IOException {
        DpmsrReportPayload payload = mapper.readValue(
                readResource("samples/hybrid-cockpit-wire-payload.json"), DpmsrReportPayload.class);
        // Same round-trip the endpoint performs: payload → built Report → XML → typed Report.
        Report built = new DpmsrReportBuilder(new ActivityReportBuilder(), null, null, null)
                .build(payload.toInput(21340));
        byte[] xml = marshaller.marshal(built);
        Report typed = marshaller.unmarshal(xml);

        ReportHeaderContext ctx = new ReportHeaderContext(
                "Sample Reporting Entity DMCC", 21340, "ae",
                "Generated by analyst@demo.local", "05 Aug 2026 12:00");
        JsonNode metadata = mapper.readTree(
                "{\"paymentMode\":\"International Wire Transfer\",\"sourceOfFunds\":\"Business income\","
                        + "\"executedBy\":\"Sample Reporting Entity DMCC\"}");

        byte[] pdf = service.render(typed, ctx, "VALID", "ae", metadata, List.of());

        assertThat(pdf).isNotNull();
        // A real PDF starts with %PDF and ends with %%EOF; a form-rich DPMSR is comfortably over a few KB.
        assertThat(new String(pdf, 0, 5, StandardCharsets.US_ASCII)).isEqualTo("%PDF-");
        assertThat(pdf.length).isGreaterThan(3000);
        assertThat(new String(pdf, StandardCharsets.ISO_8859_1)).contains("%%EOF");

        Path out = Path.of("build/DPMSR_sample_report.pdf");
        Files.createDirectories(out.getParent());
        Files.write(out, pdf);
    }

    @Test
    void rendersWithoutErrorWhenOptionalSectionsAreAbsent() throws IOException {
        DpmsrReportPayload payload = mapper.readValue(
                readResource("samples/hybrid-cockpit-wire-payload.json"), DpmsrReportPayload.class);
        Report built = new DpmsrReportBuilder(new ActivityReportBuilder(), null, null, null)
                .build(payload.toInput(21340));
        Report typed = marshaller.unmarshal(marshaller.marshal(built));

        ReportHeaderContext ctx = new ReportHeaderContext(null, 0, null, null, null);
        // no client metadata, no validation messages, thin header context
        byte[] pdf = service.render(typed, ctx, null, null, null, List.of());

        assertThat(new String(pdf, 0, 5, StandardCharsets.US_ASCII)).isEqualTo("%PDF-");
        assertThat(pdf.length).isGreaterThan(2000);
    }

    private static byte[] readResource(String path) throws IOException {
        try (InputStream in = Thread.currentThread().getContextClassLoader().getResourceAsStream(path)) {
            assertThat(in).as("test resource %s present on classpath", path).isNotNull();
            return in.readAllBytes();
        }
    }
}
